swagger: '2.0'
info:
  description: Blub
  version: '2020-03-25T20:42:49Z'
  title: Items Service
host: e86zriu8k7.execute-api.eu-west-2.amazonaws.com
basePath: /prod
schemes:
  - https
paths:
  /items:
    get:
      responses:
        '200':
          description: Ok
        '401':
          description: Authorization information is missing or invalid
      x-amazon-apigateway-integration:
        uri: >-
          arn:aws:apigateway:eu-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-2:609841182532:function:ApiLambdaCrudDynamoDBExam-getAllItemsFunction0B7A9-1N2VXS81RON6H/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
      parameters:
        - in: query
          name: userId
          description: Get all alf instances with that userId
          required: false
          type: string
    post:
      responses:
        '201':
          description: Alf instance creation initiated
        '400':
          description: >-
            Bad request. Alf Type be an integer and bigger than 0 and smaller
            than 1000.
        '401':
          description: Authorization information is missing or invalid.
      x-amazon-apigateway-request-validator: ApiLa-Defau-QLVQBYDFUBVA
      x-amazon-apigateway-integration:
        uri: >-
          arn:aws:apigateway:eu-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-2:609841182532:function:ApiLambdaCrudDynamoDBExam-createItemFunctionApi5B6-FAM0IAFIITH2/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
      parameters:
        - in: body
          name: createAlfBody
          description: Body for Alf Creation
          required: true
          schema:
            type: object
            required:
              - userId
              - alfType
            properties:
              userId:
                type: string
              alfType:
                type: integer
                minimum: 1
                maximum: 999
    options:
      consumes:
        - application/json
      responses:
        '200':
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Credentials:
              type: string
            Access-Control-Allow-Headers:
              type: string
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: '200'
            responseParameters:
              method.response.header.Access-Control-Allow-Credentials: '''false'''
              method.response.header.Access-Control-Allow-Methods: '''OPTIONS,GET,PUT,POST,DELETE'''
              method.response.header.Access-Control-Allow-Headers: >-
                'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'
              method.response.header.Access-Control-Allow-Origin: '''*'''
        requestTemplates:
          application/json: '{"statusCode": 200}'
        passthroughBehavior: never
        type: mock
  '/items/{id}':
    get:
      responses: {}
      x-amazon-apigateway-integration:
        uri: >-
          arn:aws:apigateway:eu-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-2:609841182532:function:ApiLambdaCrudDynamoDBExam-getOneItemFunctionE3257B-6G9580S5X5SK/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
    delete:
      responses: {}
      x-amazon-apigateway-integration:
        uri: >-
          arn:aws:apigateway:eu-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-2:609841182532:function:ApiLambdaCrudDynamoDBExam-deleteItemFunction2918B1-KPN18NJCFW9L/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
    options:
      consumes:
        - application/json
      responses:
        '200':
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Credentials:
              type: string
            Access-Control-Allow-Headers:
              type: string
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: '200'
            responseParameters:
              method.response.header.Access-Control-Allow-Credentials: '''false'''
              method.response.header.Access-Control-Allow-Methods: '''OPTIONS,GET,PUT,POST,DELETE'''
              method.response.header.Access-Control-Allow-Headers: >-
                'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'
              method.response.header.Access-Control-Allow-Origin: '''*'''
        requestTemplates:
          application/json: '{"statusCode": 200}'
        passthroughBehavior: never
        type: mock
    patch:
      responses: {}
      x-amazon-apigateway-integration:
        uri: >-
          arn:aws:apigateway:eu-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-2:609841182532:function:ApiLambdaCrudDynamoDBExam-updateItemFunction594152-1QBFDT2HGCC36/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
x-amazon-apigateway-request-validators:
  ApiLa-Defau-QLVQBYDFUBVA:
    validateRequestParameters: true
    validateRequestBody: true
